# Generated by Django 4.2.25 on 2025-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('haut', 'Haut'), ('bas', 'Bas'), ('pantalon', 'Pantalon'), ('short', 'Short'), ('robe', 'Robe'), ('veste', 'Veste'), ('chaussures', 'Chaussures'), ('autre', 'Autre')], max_length=20)),
                ('marque', models.CharField(max_length=120)),
                ('style', models.CharField(blank=True, max_length=120, null=True)),
                ('taille', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('photo', models.ImageField(upload_to='vetements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
